const KEY='four-weeks-strength-v10';
let state=JSON.parse(localStorage.getItem(KEY)||'{}');
state.done=state.done||{};state.notes=state.notes||{};state.session=state.session||null;
let currentView='today',workouts=[];
let sessionTimerHandle=null;
function clearSessionTimer(){if(sessionTimerHandle!==null){clearTimeout(sessionTimerHandle);sessionTimerHandle=null}}
function scheduleSessionTick(){clearSessionTimer();sessionTimerHandle=setTimeout(()=>{sessionTimerHandle=null;tickRest()},1000)}
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const fmt=d=>new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'long'}).format(new Date(d+'T12:00:00'));
const isoLocal=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const addDays=(iso,n)=>{const d=new Date(iso+'T12:00:00');d.setDate(d.getDate()+n);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const round5=n=>Math.max(5,Math.round(n/5)*5);
const dayName=date=>new Intl.DateTimeFormat('ru-RU',{weekday:'long'}).format(new Date(date+'T12:00:00')).replace('.', '');
const extraPool=[
 ['Выпады',3,'10/нога'],['Ягодичный мостик',3,'15'],['Ягодичный мостик',3,'12'],['Супермен',3,'12'],
 ['Обратные выпады',3,'10/нога'],['Скручивания',3,'15'],['Боковая планка',2,'25 сек/сторона'],['Подъёмы на носки',3,'18'],
 ['Мёртвый жук',3,'10/сторона'],['Кобра',3,'25 сек'],['Подъёмы на носки',3,'18'],['Подъёмы на носки',2,'15']
];
function extraFor(day,week){if(day%7===6)return 'Восстановление · лёгкая мобильность 8–10 мин';let e=extraPool[(day+week*2)%extraPool.length];let bump=week>=3&&/^(\d+)$/.test(e[2])?String(+e[2]+3):e[2];return `${e[0]} ${e[1]}×${bump}`}
function repSpec(max,week,type){
 const patterns={push:[[4,.42],[4,.46],[5,.48],[3,.38],[5,.52],[3,.44]],squat:[[3,.42],[4,.38],[3,.48],[2,.34],[4,.46],[3,.52]]};
 const [sets,base]=patterns[type][week.day];const factor=base+[0,.035,.07,.10][week.w-1];const floor=type==='push'?2:8,reps=Math.min(max,Math.max(1,Math.max(floor,Math.round(max*factor))));return `${sets}×${reps}`;
}
function plankSpec(max,week){const p=[[3,.60],[3,.66],[4,.58],[2,.52],[3,.72],[1,.88]][week.day];return `${p[0]}×${Math.min(max,Math.max(1,Math.max(15,round5(max*(p[1]+[0,.05,.10,.15][week.w-1])))))} сек`}
function generatePlan(base,start){
 const plan=[];
 for(let i=0;i<28;i++){
   const w=Math.floor(i/7)+1,d=i%7,date=addDays(start,i),ctx={w,day:d};
   if(i===27){plan.push({id:i+1,week:w,date,day:'День 28 · ТЕСТ',push:`1×макс. → ${Math.round(base.push*1.5)}`,squat:`1×макс. → ${Math.round(base.squat*1.5)}`,plank:`1×макс. → ${fmtTime(Math.round(base.plank*1.5))}`,extra:'Итоговый контроль'});continue}
   if(d===6){plan.push({id:i+1,week:w,date,day:dayName(date),push:'—',squat:`2×${Math.min(base.squat,Math.max(1,Math.max(10,Math.round(base.squat*.25))))}`,plank:'—',extra:extraFor(i,w)});continue}
   let push=repSpec(base.push,ctx,'push'),squat=repSpec(base.squat,ctx,'squat'),plank=plankSpec(base.plank,ctx);
   if(w===4&&d===5){push='—';squat='—';plank='—'}
   if(w===4&&d===4){push=`2×${Math.min(base.push,Math.max(1,Math.max(2,Math.round(base.push*.30))))}`;squat=`2×${Math.min(base.squat,Math.max(1,Math.max(8,Math.round(base.squat*.25))))}`;plank=`1×${Math.min(base.plank,Math.max(1,Math.max(15,round5(base.plank*.45))))} сек`}
   plan.push({id:i+1,week:w,date,day:dayName(date),push,squat,plank,extra:w===4&&d===5?'Лёгкая растяжка всего тела 10 мин':extraFor(i,w)});
 }
 return plan;
}
function hydratePlan(){workouts=state.profile?generatePlan(state.profile,state.startDate):[]}
function fmtTime(sec){sec=Math.max(0,Number(sec)||0);return `${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
function onboarding(){return `<section class="onboarding"><p class="eyebrow">Персональная программа</p><h2>Сначала замерим твой максимум</h2><p class="onboarding-lead">Выполни по одному контрольному подходу в комфортных условиях. Введи максимальное количество качественных повторений и время планки. На их основе приложение построит программу на 4 недели с ориентиром примерно <strong>×1,5</strong>.</p><form id="baselineForm" class="baseline-form"><label><span>Имя</span><input name="name" type="text" maxlength="40" autocomplete="name" placeholder="Как тебя зовут?"><small>будет отображаться в профиле</small></label><label><span>Отжимания</span><input name="push" type="number" min="1" max="300" required placeholder="например, 18"><small>максимум повторений</small></label><label><span>Приседания</span><input name="squat" type="number" min="1" max="500" required placeholder="например, 60"><small>максимум повторений</small></label><label><span>Планка</span><div class="time-input"><input name="plankMin" type="number" min="0" max="20" value="0" required><b>мин</b><input name="plankSec" type="number" min="0" max="59" placeholder="40" required><b>сек</b></div><small>максимальное удержание</small></label><button class="check-btn" type="submit">Составить мой план</button></form></section>`}
function renderOnboarding(){document.querySelector('.main-nav').classList.add('hidden');document.querySelector('.progress-card').classList.add('hidden');document.querySelector('#todayView').classList.remove('hidden');document.querySelector('#planView').classList.add('hidden');document.querySelector('#profileView').classList.add('hidden');document.querySelector('#todayStatus').innerHTML='';document.querySelector('#todayWorkout').innerHTML=onboarding();document.querySelector('#baselineForm').onsubmit=e=>{e.preventDefault();let f=new FormData(e.currentTarget),name=String(f.get('name')||'').trim(),push=+f.get('push'),squat=+f.get('squat'),plank=+f.get('plankMin')*60+(+f.get('plankSec'));if(plank<10)return alert('Для планки укажи время не меньше 10 секунд.');state={profile:{name,push,squat,plank},startDate:addDays(isoLocal(),1),done:{},notes:{},session:null};save();hydratePlan();render()}}
function card(w,big=false){return `<article class="workout ${big?'featured':''} ${state.done[w.id]?'done':''}"><div class="workout-top"><div><p class="date">${fmt(w.date)} · Неделя ${w.week}</p><h3>${w.day}${w.day.includes('ТЕСТ')?'':' <span class="badge">20–30 мин</span>'}</h3></div>${!big?`<button class="complete" data-id="${w.id}">${state.done[w.id]?'✓ Выполнено':'Выполнить'}</button>`:''}</div><div class="exercise-grid"><div class="exercise"><span>Отжимания</span><strong>${w.push}</strong></div><div class="exercise"><span>Приседания</span><strong>${w.squat}</strong></div><div class="exercise"><span>Планка</span><strong>${w.plank}</strong></div><div class="exercise"><span>Дополнительно</span><strong>${w.extra}</strong></div></div>${big&&!state.done[w.id]?`<button class="start-workout" data-start="${w.id}">▶ Начать тренировку</button>`:''}${big&&state.done[w.id]?`<button class="complete primary-complete" data-id="${w.id}">✓ Тренировка выполнена</button>`:''}</article>`}
function showCompletion(){const c=state.lastCompletion;if(!c)return;let mins=Math.floor(c.duration/60),secs=c.duration%60,pct=Math.round(c.programDone/c.programTotal*100),overlay=document.querySelector('#completionOverlay');if(!overlay){overlay=document.createElement('div');overlay.id='completionOverlay';overlay.className='completion-overlay';document.body.appendChild(overlay)}overlay.innerHTML=`<div class="completion-card"><div class="completion-mark">✓</div><p class="eyebrow">Тренировка завершена</p><h2>Отличная работа!</h2><p class="completion-sub">Ещё один день программы выполнен.</p><div class="completion-stats"><article><span>Время</span><strong>${String(mins).padStart(2,'0')}:${String(secs).padStart(2,'0')}</strong></article><article><span>Подходы</span><strong>${c.sets}</strong></article><article><span>Программа</span><strong>${pct}%</strong></article></div><div class="completion-progress"><i style="width:${pct}%"></i></div><small>${c.programDone} из ${c.programTotal} дней отмечено выполненными</small><button class="check-btn" id="closeCompletion">Готово</button></div>`;requestAnimationFrame(()=>overlay.classList.add('show'));document.querySelector('#closeCompletion').onclick=()=>{overlay.classList.remove('show');setTimeout(()=>overlay.remove(),220)}}
function renderToday(){const today=isoLocal(),first=workouts[0],last=workouts.at(-1);let w=workouts.find(x=>x.date===today),msg='';if(today<first.date){w=first;msg=`План стартует ${fmt(first.date)}.`}else if(today>last.date){w=last;msg='Четырёхнедельный план завершён. Ниже — итоговый тест.'}else if(!w){w=workouts.find(x=>x.date>today)||last;msg=`Ближайшая тренировка — ${fmt(w.date)}.`}else msg=state.done[w.id]?'Сегодняшняя тренировка уже отмечена.':'Персональная тренировка на сегодня готова.';document.querySelector('#todayStatus').innerHTML=`<span class="status-dot"></span><div><strong>${today===w.date?'Сегодня':'Ближайшая тренировка'}</strong><p>${msg}</p></div>`;document.querySelector('#todayWorkout').innerHTML=state.session&&state.session.id===w.id?sessionHTML(w):card(w,true)}
function completedWorkouts(){return workouts.filter(w=>state.done[w.id]).length}
function plankTotal(spec){const m=String(spec||'').match(/^(\d+)×(\d+)\s*сек/);return m?Number(m[1])*Number(m[2]):0}
function userStats(){let push=0,squat=0,plank=0;for(const w of workouts){if(!state.done[w.id])continue;push+=specTotal(w.push);squat+=specTotal(w.squat);plank+=plankTotal(w.plank)}return {workouts:completedWorkouts(),push,squat,plank}}
function renderProfile(){const el=document.querySelector('#profileView');if(!el||!state.profile)return;const b=state.profile,s=userStats(),t={push:Math.round(b.push*1.5),squat:Math.round(b.squat*1.5),plank:Math.round(b.plank*1.5)},name=String(b.name||'').trim();el.innerHTML=`<section class="profile-page"><p class="eyebrow">Личный профиль</p><div class="profile-heading"><div><h2>${name||'Твой профиль'}</h2><p>Статистика считается по завершённым тренировкам.</p></div>${name?'':`<button class="secondary" id="setProfileName">Добавить имя</button>`}</div><div class="profile-stats"><article><span>Тренировок</span><strong>${s.workouts}</strong></article><article><span>Отжиманий</span><strong>${s.push}</strong></article><article><span>Приседаний</span><strong>${s.squat}</strong></article><article><span>Секунд в планке</span><strong>${s.plank}</strong></article></div><div class="profile-targets"><p class="eyebrow">Целевые показатели ×1,5</p><h3>Твои ориентиры</h3><div class="goal-grid"><article class="goal-card"><span>Отжимания</span><strong>${t.push}</strong><small>Старт: ${b.push}</small></article><article class="goal-card"><span>Приседания</span><strong>${t.squat}</strong><small>Старт: ${b.squat}</small></article><article class="goal-card"><span>Планка</span><strong>${fmtTime(t.plank)}</strong><small>Старт: ${fmtTime(b.plank)}</small></article></div></div></section>`;const btn=document.querySelector('#setProfileName');if(btn)btn.onclick=()=>{const v=prompt('Как тебя зовут?',state.profile.name||'');if(v!==null){state.profile.name=String(v).trim().slice(0,40);save();renderProfile()}}}
function renderReading(){const el=document.querySelector('#readingView');if(!el)return;el.innerHTML=`<section class="reading-page"><p class="eyebrow">Чтиво</p><h2>Коротко о полезном</h2><p class="reading-lead">Без магии и фитнес-мифов — практические вещи для этой программы.</p>
<article class="reading-card"><div class="reading-num">01</div><div><h3>Вода утром: полезная привычка, но не суперсила</h3><p>После сна нормально хотеть пить: несколько часов организм не получал жидкость. Стакан воды утром — простой способ начать восполнять её, особенно перед тренировкой. Но доказательств, что вода именно натощак создаёт особый «детокс» или требует обязательных 500 мл, нет.</p><p>Важнее пить достаточно в течение дня. Потребность зависит от активности, жары, питания и здоровья. Практичные ориентиры — жажда и светло-жёлтый цвет мочи. При тренировках и заметном потоотделении жидкости обычно требуется больше.</p><div class="reading-tip"><b>Перед утренней тренировкой:</b> если хочется пить — выпей воды. Не нужно заставлять себя пить большой объём залпом.</div><p class="reading-source">По материалам Mayo Clinic, NHS и National Academies.</p></div></article>
<article class="reading-card"><div class="reading-num">02</div><div><h3>Отдых между подходами — часть тренировки</h3><p>Пауза помогает следующему подходу снова быть качественным. При слишком коротком отдыхе усталость накапливается, количество повторений и тренировочный объём могут снижаться.</p><p>Для силы более длинные интервалы часто полезнее: систематический обзор показывает, что у тренированных людей паузы больше 2 минут могут лучше поддерживать прирост силы, тогда как у новичков часто достаточно 60–120 секунд. Мета-анализ 2024 года по гипертрофии обнаружил небольшой возможный плюс отдыха дольше 60 секунд; заметного дополнительного преимущества после примерно 90 секунд авторы не выявили.</p><div class="reading-tip"><b>Практически:</b> после обычного подхода ориентируйся примерно на 60–90 секунд; после тяжёлого — на 2 минуты и больше. Если дыхание и техника ещё не восстановились, лучше добавить немного отдыха.</div><p class="reading-source">По систематическим обзорам исследований силовых тренировок.</p></div></article></section>`;}
function bind(){document.querySelectorAll('.complete').forEach(b=>b.onclick=()=>{let id=b.dataset.id;state.done[id]=!state.done[id];save();render()});document.querySelectorAll('.notes').forEach(n=>n.oninput=()=>{state.notes[n.dataset.note]=n.value;save()});document.querySelectorAll('[data-start]').forEach(e=>e.onclick=()=>startSession(+e.dataset.start));document.querySelectorAll('[data-session-action]').forEach(e=>e.onclick=sessionAction);document.querySelectorAll('.main-tab').forEach(b=>b.onclick=()=>{currentView=b.dataset.view;render()})}
function render(){
 if(!state.profile){renderOnboarding();syncWelcome();return}
 hydratePlan();
 document.querySelector('.main-nav').classList.remove('hidden');
 document.querySelector('.progress-card').classList.remove('hidden');
 document.querySelector('.hero .eyebrow').textContent=`${fmt(workouts[0].date)} — ${fmt(workouts.at(-1).date)}`;
 const doneCount=workouts.filter(w=>state.done[w.id]).length,pct=Math.round(doneCount/workouts.length*100);
 document.querySelector('#progressText').textContent=`${doneCount} / ${workouts.length}`;
 document.querySelector('#progressBar').style.width=pct+'%';
 document.querySelector('#progressPercent').textContent=`${pct}% плана выполнено`;
 ['today','plan','reading','profile','achievements'].forEach(v=>document.querySelector('#'+v+'View')?.classList.toggle('hidden',currentView!==v));
 document.querySelectorAll('.main-tab').forEach(b=>b.classList.toggle('active',b.dataset.view===currentView));
 renderToday(); renderProfile(); renderPlan(); renderAchievements(); renderReading(); bind(); syncWelcome();
}
function renderPlan(){
 const summary=document.querySelector('#weekSummary');
 if(summary) summary.innerHTML=`<span>Все 28 дней · ${fmt(workouts[0].date)} — ${fmt(workouts.at(-1).date)}</span><strong>${workouts.filter(w=>state.done[w.id]).length} / 28 выполнено</strong>`;
 const tabs=document.querySelector('#weekTabs'); if(tabs) tabs.innerHTML='';
 document.querySelector('#workouts').innerHTML=workouts.map(w=>card(w)).join('');
}
function specTotal(spec){
 const m=String(spec||'').match(/^(\d+)×(\d+)(?:\s|$)/); return m?Number(m[1])*Number(m[2]):0;
}
function achievementProgress(){
 let push=0,squat=0;
 for(const w of workouts){if(state.done[w.id]){push+=specTotal(w.push);squat+=specTotal(w.squat)}}
 const done=completedWorkouts();return {measure:state.profile?1:0,steady:done>0?1:0,squats500:Math.min(500,squat),pushups100:Math.min(100,push),week1:Math.min(7,done),week2:Math.min(14,done),week3:Math.min(21,done),week4:Math.min(28,done)};
}
const ACHIEVEMENTS=[
 {id:'measure',title:'Замер',desc:'Провести первый стартовый замер',img:'achievement-measure.jpg',goal:1},
 {id:'steady',title:'Планомерно',desc:'Завершить первую тренировку',img:'achievement-steady.jpg',goal:1},
 {id:'squats500',title:'Давид и Ч.',desc:'Выполнить 500 приседаний',img:'achievement-squats.jpg',goal:500},
 {id:'pushups100',title:'Мастер Отжиманий',desc:'Выполнить 100 отжиманий',img:'achievement-pushups.jpg',goal:100},
 {id:'week1',title:'1 Неделя',desc:'Завершить 7 тренировок',img:'achievement-week1.jpg',goal:7},
 {id:'week2',title:'2 Неделя',desc:'Завершить 14 тренировок',img:'achievement-week2.jpg',goal:14},
 {id:'week3',title:'3 Неделя',desc:'Завершить 21 тренировку',img:'achievement-week3.jpg',goal:21},
 {id:'week4',title:'4 Неделя',desc:'Завершить 28 тренировок',img:'achievement-week4.jpg',goal:28}
];
function renderAchievements(){
 const grid=document.querySelector('#achievementsGrid'); if(!grid||!state.profile)return;
 const p=achievementProgress();
 grid.innerHTML=ACHIEVEMENTS.map(a=>{const value=p[a.id],pct=Math.min(100,Math.round(value/a.goal*100)),ok=value>=a.goal;return `<article class="achievement-card ${ok?'unlocked':'locked'}"><div class="achievement-art"><img src="${a.img}" alt="${a.title}">${ok?'':'<span class="achievement-state">🔒</span>'}</div><div class="achievement-copy"><h3>${a.title}</h3><p>${a.desc}</p><div class="achievement-progress"><div style="width:${pct}%"></div></div><div class="achievement-numbers"><b>${value} / ${a.goal}</b><span>${pct}%</span></div></div></article>`}).join('');
}
function syncWelcome(){
 const w=document.querySelector('#welcomeV12'); if(!w)return;
 const shouldShow=!state.profile && !sessionStorage.getItem('welcomeDismissed');
 w.classList.toggle('hidden',!shouldShow); document.body.classList.toggle('onboarding-open',shouldShow);
}
document.querySelector('#resetBtn').onclick=()=>{if(confirm('Сбросить персональную программу, результаты и пройти стартовый тест заново?')){localStorage.removeItem(KEY);sessionStorage.removeItem('welcomeDismissed');state={done:{},notes:{},session:null};workouts=[];currentView='today';render()}};
function parseSpec(name,spec){if(!spec||spec==='—')return[];let m=spec.match(/(\d+)×(.+)/);if(!m)return[{name,target:spec,rest:60}];let n=+m[1],target=m[2].trim();return Array.from({length:n},(_,i)=>({name,target:`${target} · подход ${i+1}/${n}`,rest:60}))}
function extraParts(extra){const m=extra.match(/^(.+?)\s+(\d+×.+)$/);return m?{name:m[1].trim(),spec:m[2].trim()}:{name:extra,spec:extra}}
function stepsFor(w){const ex=extraParts(w.extra),groups=[parseSpec('Отжимания',w.push),parseSpec('Приседания',w.squat),parseSpec('Планка',w.plank),parseSpec(ex.name,ex.spec)].filter(g=>g.length),steps=[],max=Math.max(0,...groups.map(g=>g.length));for(let round=0;round<max;round++)groups.forEach(g=>{if(g[round])steps.push({...g[round],round:round+1,rest:35})});return steps.map((s,i)=>({...s,next:i<steps.length-1?steps[i+1].name:null}))}
function startSession(id){clearSessionTimer();state.session={id,index:0,phase:'ready',remaining:0,startedAt:Date.now(),completedSets:0};save();render()}
function timedSeconds(step){if(!step)return 0;const m=String(step.target||'').match(/(\d+)(?:[–-](\d+))?\s*сек/);return m?Number(m[2]||m[1]):0}
function sessionHTML(w){let s=state.session,steps=stepsFor(w);if(!steps.length)return card(w,true);let st=steps[Math.min(s.index,steps.length-1)],pct=Math.round(s.index/steps.length*100),maxRound=Math.max(...steps.map(x=>x.round||1)),countdown=['rest','prepare','exercise'].includes(s.phase);if(countdown)scheduleSessionTick();else clearSessionTimer();let total=s.phase==='prepare'?5:s.phase==='exercise'?timedSeconds(st):35,timerPct=countdown?Math.max(0,Math.min(1,s.remaining/Math.max(1,total))):1,circ=289,timed=timedSeconds(st)>0,label=s.phase==='prepare'?'Займите правильное положение':s.phase==='exercise'?'Выполняйте упражнение':'Переход к следующему упражнению';return `<section class="session"><div class="session-head"><span>Круг ${st.round||1} из ${maxRound} · шаг ${Math.min(s.index+1,steps.length)} из ${steps.length}</span></div><div class="session-progress"><div style="width:${pct}%"></div></div>${countdown?`<div class="rest ${s.phase}"><p class="rest-label">${label}</p><div class="timer-ring"><svg viewBox="0 0 104 104"><circle class="ring-bg" cx="52" cy="52" r="46"/><circle class="ring-fg" cx="52" cy="52" r="46" style="stroke-dasharray:${circ};stroke-dashoffset:${circ*(1-timerPct)}"/></svg><div class="timer-small">${fmtTime(s.remaining)}</div></div>${s.phase==='rest'?`<div class="up-next"><span>Следом</span><strong>${st.name}</strong><small>${st.target}</small></div>`:`<div class="timed-caption">${s.phase==='prepare'?'После 5 секунд подготовки рабочий таймер запустится автоматически.':`Время подхода: ${fmtTime(timedSeconds(st))}`}</div>`}<button class="secondary wide" data-session-action="skip">${s.phase==='prepare'?'Пропустить подготовку':s.phase==='exercise'?'Завершить раньше':'Пропустить отдых'}</button></div>`:`<div class="active-step"><div class="round-chip">КРУГ ${st.round||1}</div><h2>${st.name}</h2><div class="target">${st.target}</div><p>${s.phase==='ready'?(timed?'После «Приступить» начнётся 00:05 на подготовку, затем рабочий таймер.':'Следующее упражнение готово.'):'Выполни подход и отметь его.'}</p>${st.next&&s.phase==='active'?`<div class="next-hint">Дальше: <strong>${st.next}</strong></div>`:''}<button class="check-btn" data-session-action="${s.phase==='ready'?'go':'done'}">${s.phase==='ready'?'▶ Приступить':'✓ Готово'}</button></div>`}<div class="session-actions"><button class="secondary" data-session-action="exit">Выйти из режима</button></div></section>`}
function advanceSession(w,steps){clearSessionTimer();let s=state.session;s.completedSets=(s.completedSets||0)+1;s.index++;if(s.index>=steps.length){state.done[w.id]=true;const doneCount=Object.values(state.done||{}).filter(Boolean).length;state.lastCompletion={id:w.id,duration:Math.max(1,Math.round((Date.now()-(s.startedAt||Date.now()))/1000)),sets:s.completedSets,total:steps.length,programDone:doneCount,programTotal:workouts.length,at:Date.now()};state.session=null;save();render();showCompletion();return true}s.phase='rest';s.remaining=35;return false}
function sessionAction(e){clearSessionTimer();let a=e.currentTarget.dataset.sessionAction,s=state.session;if(!s)return;let w=workouts.find(x=>x.id===s.id),steps=stepsFor(w),st=steps[Math.min(s.index,steps.length-1)];if(a==='go'){if(timedSeconds(st)){s.phase='prepare';s.remaining=5}else s.phase='active'}if(a==='done'&&advanceSession(w,steps))return;if(a==='skip'){if(s.phase==='prepare'){s.phase='exercise';s.remaining=timedSeconds(st)}else if(s.phase==='exercise'){if(advanceSession(w,steps))return}else{s.phase='ready';s.remaining=0}}if(a==='exit')state.session=null;save();render()}
function tickRest(){clearSessionTimer();let s=state.session;if(!s||!['rest','prepare','exercise'].includes(s.phase))return;if(s.remaining>0){s.remaining--;save();render();return}let w=workouts.find(x=>x.id===s.id),steps=stepsFor(w),st=steps[Math.min(s.index,steps.length-1)];if(s.phase==='prepare'){s.phase='exercise';s.remaining=timedSeconds(st)}else if(s.phase==='exercise'){if(advanceSession(w,steps))return}else s.phase='ready';save();render()}
render();



document.addEventListener('click',e=>{if(e.target?.id==='welcomeStart'){sessionStorage.setItem('welcomeDismissed','1');syncWelcome();document.querySelector('#baselineForm input')?.scrollIntoView({behavior:'smooth',block:'center'});}});
